development:
  adapter: mysql2
  encoding: utf8
  database: logger_development
  username: root
  password:
test:
  adapter: mysql2
  encoding: utf8
  database: logger_test
  username: root
  password:

