projects:
    - name: internal_apps
      client_name: BeautifulCode
    - name: RevDirect
      client_name: Sojern
    - name: Debtinator
      client_name: Sojern
    - name: Learning
      client_name: Learning
    - name: Navigator
      client_name: Sojern


